### ISSUE TITLE
OpenCore 0.8.2 roadmap

### ISSUE THREAD

**Issue by dreamwhite** [GopnikOutlanders/OpenCore-Install-Guide#1]
The following issue is opened to keep track of the necessary changes to adapt the old guide to OpenCore 0.8.2:

- [ ] Introduction
    - [ ] Getting started with OpenCore
        - [ ] Prerequisites
    - [ ] Hardware Limitations
        - [ ] CPU Support
        - [ ] GPU Support
        - [ ] Motherboard Support
        - [ ] Storage Support
        - [ ] Wired Networking
        - [ ] Wireless Networking
        - [ ] Miscellaneous
    - [ ] Finding your hardware
        - [ ] Finding your hardware using Windows
        - [ ] Finding your hardware using Linux
        - [ ] Finding your hardware using OCSysInfo
    - [ ] Terminology
    - [ ] Why OpenCore over Clover and others
        - [ ] OpenCore features
        - [ ] OpenCore's shortcoming
        - [ ] Common myths

- [ ] USB Creation
    - [ ] Creating the USB
        - [ ] Making the installer in macOS
            - [ ] Downloading macOS: Modern OS
            - [ ] Downloading macOS: Legacy OS
            - [ ] Setting up the installer
            - [ ] Legacy Setup
            - [ ] Setting up OpenCore's EFI environment
            - [ ] Now with all of this done, head to Setting up the EFI to finish up your work
        - [ ] Making the installer in Windows
            - [ ] Downloading macOS
            - [ ] Making the installer
            - [ ] Now with all this done, head to Setting up the EFI to finish up your work
        - [ ] Making the installer in Linux
            - [ ] Downloading macOS
            - [ ] Making the installer
            - [ ] Now with all this done, head to Setting up the EFI to finish up your work
    - [ ] Adding The Base OpenCore files
    - [ ] Gathering files
        - [ ] Firmware drivers
            - [ ] Universal
            - [ ] Legacy users
        - [ ] Kexts
            - [ ] Must haves
            - [ ] VirtualSMC plugins
            - [ ] Graphics
            - [ ] Audio
            - [ ] Ethernet
            - [ ] USB
            - [ ] WiFi and Bluetooth
            - [ ] AMD CPU Specific kexts
            - [ ] Extras
            - [ ] Laptop Input
        - [ ] SSDTs
            - [ ] Desktop
            - [ ] High End Desktop
            - [ ] Laptop
    - [ ] Getting started with ACPI
    - [ ] config.plist Setup
        - [ ] Creating your config.plist
        - [ ] Adding your SSDTs, Kexts and Firmware Drivers
        - [ ] Selecting your platform
            - [ ] Intel Desktop
            - [ ] Intel Laptop
            - [ ] Intel HEDT
            - [ ] AMD
- [ ] Configs
    - [ ] Intel Desktop config.plist
        - [ ] Penryn
            - [ ] Starting point
            - [ ] ACPI
            - [ ] Booter
            - [ ] DeviceProperties
            - [ ] Kernel
            - [ ] Misc
            - [ ] NVRAM
            - [ ] PlatformInfo
            - [ ] UEFI
            - [ ] Cleaning up
            - [ ] Intel BIOS settings
        - [ ] Clarkdale
            - [ ] Starting point
            - [ ] ACPI
            - [ ] Booter
            - [ ] DeviceProperties
            - [ ] Kernel
            - [ ] Misc
            - [ ] NVRAM
            - [ ] PlatformInfo
            - [ ] UEFI
            - [ ] Cleaning up
            - [ ] Intel BIOS settings
        - [ ] Sandy Bridge
            - [ ] Starting point
            - [ ] ACPI
            - [ ] Booter
            - [ ] DeviceProperties
            - [ ] Kernel
            - [ ] Misc
            - [ ] NVRAM
            - [ ] PlatformInfo
            - [ ] UEFI
            - [ ] Cleaning up
            - [ ] Intel BIOS settings
        - [ ] Ivy Bridge
            - [ ] Starting point
            - [ ] ACPI
            - [ ] Booter
            - [ ] DeviceProperties
            - [ ] Kernel
            - [ ] Misc
            - [ ] NVRAM
            - [ ] PlatformInfo
            - [ ] UEFI
            - [ ] Cleaning up
            - [ ] Intel BIOS settings
        - [ ] Haswell
            - [ ] Starting point
            - [ ] ACPI
            - [ ] Booter
            - [ ] DeviceProperties
            - [ ] Kernel
            - [ ] Misc
            - [ ] NVRAM
            - [ ] PlatformInfo
            - [ ] UEFI
            - [ ] Cleaning up
            - [ ] Intel BIOS settings
         - [ ] Skylake
            - [ ] Starting point
            - [ ] ACPI
            - [ ] Booter
            - [ ] DeviceProperties
            - [ ] Kernel
            - [ ] Misc
            - [ ] NVRAM
            - [ ] PlatformInfo
            - [ ] UEFI
            - [ ] Cleaning up
            - [ ] Intel BIOS settings
        - [ ] Kaby Lake
            - [ ] Starting point
            - [ ] ACPI
            - [ ] Booter
            - [ ] DeviceProperties
            - [ ] Kernel
            - [ ] Misc
            - [ ] NVRAM
            - [ ] PlatformInfo
            - [ ] UEFI
            - [ ] Cleaning up
            - [ ] Intel BIOS settings
        - [ ] Coffee Lake
            - [ ] Starting point
            - [ ] ACPI
            - [ ] Booter
            - [ ] DeviceProperties
            - [ ] Kernel
            - [ ] Misc
            - [ ] NVRAM
            - [ ] PlatformInfo
            - [ ] UEFI
            - [ ] Cleaning up
            - [ ] Intel BIOS settings
        - [ ] Comet Lake
            - [ ] Starting point
            - [ ] ACPI
            - [ ] Booter
            - [ ] DeviceProperties
            - [ ] Kernel
            - [ ] Misc
            - [ ] NVRAM
            - [ ] PlatformInfo
            - [ ] UEFI
            - [ ] Cleaning up
            - [ ] Intel BIOS settings
        - [ ] Rocket Lake
            - [ ] Starting point
            - [ ] ACPI
            - [ ] Booter
            - [ ] DeviceProperties
            - [ ] Kernel
            - [ ] Misc
            - [ ] NVRAM
            - [ ] PlatformInfo
            - [ ] UEFI
            - [ ] Cleaning up
            - [ ] Intel BIOS settings
        - [ ] Alder Lake
            - [ ] Starting point
            - [ ] ACPI
            - [ ] Booter
            - [ ] DeviceProperties
            - [ ] Kernel
            - [ ] Misc
            - [ ] NVRAM
            - [ ] PlatformInfo
            - [ ] UEFI
            - [ ] Cleaning up
            - [ ] Intel BIOS settings
    - [ ] Intel Laptop config.plist
        - [ ] Arrandale
            - [ ] Starting point
            - [ ] ACPI
            - [ ] Booter
            - [ ] DeviceProperties
            - [ ] Kernel
            - [ ] Misc
            - [ ] NVRAM
            - [ ] PlatformInfo
            - [ ] UEFI
            - [ ] Cleaning up
            - [ ] Intel BIOS settings
        - [ ] Sandy Bridge
            - [ ] Starting point
            - [ ] ACPI
            - [ ] Booter
            - [ ] DeviceProperties
            - [ ] Kernel
            - [ ] Misc
            - [ ] NVRAM
            - [ ] PlatformInfo
            - [ ] UEFI
            - [ ] Cleaning up
            - [ ] Intel BIOS settings
        - [ ] Ivy Bridge
            - [ ] Starting point
            - [ ] ACPI
            - [ ] Booter
            - [ ] DeviceProperties
            - [ ] Kernel
            - [ ] Misc
            - [ ] NVRAM
            - [ ] PlatformInfo
            - [ ] UEFI
            - [ ] Cleaning up
            - [ ] Intel BIOS settings
        - [ ] Haswell
            - [ ] Starting point
            - [ ] ACPI
            - [ ] Booter
            - [ ] DeviceProperties
            - [ ] Kernel
            - [ ] Misc
            - [ ] NVRAM
            - [ ] PlatformInfo
            - [ ] UEFI
            - [ ] Cleaning up
            - [ ] Intel BIOS settings
        - [ ] Broadwell
            - [ ] Starting point
            - [ ] ACPI
            - [ ] Booter
            - [ ] DeviceProperties
            - [ ] Kernel
            - [ ] Misc
            - [ ] NVRAM
            - [ ] PlatformInfo
            - [ ] UEFI
            - [ ] Cleaning up
            - [ ] Intel BIOS settings
        - [ ] Skylake
            - [ ] Starting point
            - [ ] ACPI
            - [ ] Booter
            - [ ] DeviceProperties
            - [ ] Kernel
            - [ ] Misc
            - [ ] NVRAM
            - [ ] PlatformInfo
            - [ ] UEFI
            - [ ] Cleaning up
            - [ ] Intel BIOS settings
        - [ ] Kaby Lake
            - [ ] Starting point
            - [ ] ACPI
            - [ ] Booter
            - [ ] DeviceProperties
            - [ ] Kernel
            - [ ] Misc
            - [ ] NVRAM
            - [ ] PlatformInfo
            - [ ] UEFI
            - [ ] Cleaning up
            - [ ] Intel BIOS settings
        - [ ] Coffee Lake and Whiskey Lake
            - [ ] Starting point
            - [ ] ACPI
            - [ ] Booter
            - [ ] DeviceProperties
            - [ ] Kernel
            - [ ] Misc
            - [ ] NVRAM
            - [ ] PlatformInfo
            - [ ] UEFI
            - [ ] Cleaning up
            - [ ] Intel BIOS settings
        - [ ] Coffee Lake Plus and Comet Lake
            - [ ] Starting point
            - [ ] ACPI
            - [ ] Booter
            - [ ] DeviceProperties
            - [ ] Kernel
            - [ ] Misc
            - [ ] NVRAM
            - [ ] PlatformInfo
            - [ ] UEFI
            - [ ] Cleaning up
            - [ ] Intel BIOS settings
        - [ ] Ice Lake
            - [ ] Starting point
            - [ ] ACPI
            - [ ] Booter
            - [ ] DeviceProperties
            - [ ] Kernel
            - [ ] Misc
            - [ ] NVRAM
            - [ ] PlatformInfo
            - [ ] UEFI
            - [ ] Cleaning up
            - [ ] Intel BIOS settings
    - [ ] Intel HEDT config.plist
        - [ ] Nehalem and Westmere
            - [ ] Starting point
            - [ ] ACPI
            - [ ] Booter
            - [ ] DeviceProperties
            - [ ] Kernel
            - [ ] Misc
            - [ ] NVRAM
            - [ ] PlatformInfo
            - [ ] UEFI
            - [ ] Cleaning up
            - [ ] Intel BIOS settings
        - [ ] Sandy and Ivy Bridge-E
            - [ ] Starting point
            - [ ] ACPI
            - [ ] Booter
            - [ ] DeviceProperties
            - [ ] Kernel
            - [ ] Misc
            - [ ] NVRAM
            - [ ] PlatformInfo
            - [ ] UEFI
            - [ ] Cleaning up
            - [ ] Intel BIOS settings
        - [ ] Haswell-E
            - [ ] Starting point
            - [ ] ACPI
            - [ ] Booter
            - [ ] DeviceProperties
            - [ ] Kernel
            - [ ] Misc
            - [ ] NVRAM
            - [ ] PlatformInfo
            - [ ] UEFI
            - [ ] Cleaning up
            - [ ] Intel BIOS settings
        - [ ] Broadwell-E
            - [ ] Starting point
            - [ ] ACPI
            - [ ] Booter
            - [ ] DeviceProperties
            - [ ] Kernel
            - [ ] Misc
            - [ ] NVRAM
            - [ ] PlatformInfo
            - [ ] UEFI
            - [ ] Cleaning up
            - [ ] Intel BIOS settings
        - [ ] Skylake-X/W and Cascade Lake-X/W
            - [ ] Starting point
            - [ ] ACPI
            - [ ] Booter
            - [ ] DeviceProperties
            - [ ] Kernel
            - [ ] Misc
            - [ ] NVRAM
            - [ ] PlatformInfo
            - [ ] UEFI
            - [ ] Cleaning up
            - [ ] Intel BIOS settings
    - [ ] AMD Desktop config.plist
        - [ ] Bulldozer(15h) and Jaguar(16h)
            - [ ] Starting point
            - [ ] ACPI
            - [ ] Booter
            - [ ] DeviceProperties
            - [ ] Kernel
            - [ ] Misc
            - [ ] NVRAM
            - [ ] PlatformInfo
            - [ ] UEFI
            - [ ] Cleaning up
            - [ ] AMD BIOS settings
        - [ ] Ryzen and Threadripper(17h and 19h)
            - [ ] Starting point
            - [ ] ACPI
            - [ ] Booter
            - [ ] DeviceProperties
            - [ ] Kernel
            - [ ] Misc
            - [ ] NVRAM
            - [ ] PlatformInfo
            - [ ] UEFI
            - [ ] Cleaning up
            - [ ] AMD BIOS settings
    - [ ] Apple Secure Boot
        - [ ] Misc

- [ ] Installation
    - [ ] Installation process
        - [ ] Double checking your work
        - [ ] Booting the OpenCore USB
        - [ ] macOS Installer

- [ ] Troubleshooting
    - [ ] General troubleshooting
        - [ ] Table of contents
        - [ ] OpenCore Boot Issues
            - [ ] Stuck on a black screen before picker
            - [ ] Stuck on no vault provided!
            - [ ] Stuck on OC: Invalid Vault mode
            - [ ] Can't see macOS partitions
            - [ ] Stuck on OCB: OcScanForBootEntries failure - Not Found
            - [ ] Stuck on OCB: failed to match a default boot option
            - [ ] Stuck on OCB: System has no boot entries
            - [ ] Stuck on OCS: No schema for DSDT, KernelAndKextPatch, RtVariable, SMBIOS, SystemParameters...
            - [ ] Stuck on OC: Driver XXX.efi at 0 cannot be found
            - [ ] Receiving "Failed to parse real field of type 1"
            - [ ] Can't select anything in the picker
            - [ ] SSDTs not being added
            - [ ] Booting OpenCore reboots to BIOS
            - [ ] OCABC: Incompatible OpenRuntime r4, require r10
            - [ ] Failed to open OpenCore image - Access Denied
            - [ ] OC: Failed to find SB model disable halting on critical error
        - [ ] Kernelspace Issues
            - [ ] Stuck on [EB|#LOG:EXITBS:START]
                - [ ] Booter Issues
                - [ ] Kernel Patch Issues
                - [ ] UEFI Issues
            - [ ] Stuck on EndRandomSeed
            - [ ] Stuck after selecting macOS partition in OpenCore
            - [ ] Kernel Panic on Invalid frame pointer
            - [ ] Stuck on [EB|LD:OFS] Err(0xE) when booting preboot volume
            - [ ] Stuck on OCB: LoadImage failed - Security Violation
            - [ ] Stuck on OCABC: Memory pool allocation failure - Not Found
            - [ ] Stuck on Buffer Too Small
            - [ ] Stuck on Plist only kext has CFBundleExecutable key
            - [ ] Stuck on This version of Mac OS X is not supported: Reason Mac...
            - [ ] Couldn't allocate runtime area errors
            - [ ] Stuck on RTC..., PCI Configuration Begins, Previous Shutdown..., HPET, HID: Legacy...
            - [ ] Stuck at ACPI table loading on B550
            - [ ] "Waiting for Root Device" or Prohibited Sign error
                - [ ] USB Issues
                - [ ] SATA Issues
            - [ ] Kernel panic with IOPCIFamily on X99
            - [ ] Stuck on or near IOConsoleUsers: gIOScreenLock.../gIOLockState (3...
            - [ ] Scrambled Screen on laptops
            - [ ] Black screen after IOConsoleUsers: gIOScreenLock... on Navi
            - [ ] Kernel Panic Cannot perform kext summary
            - [ ] Kernel Panic AppleIntelMCEReporter
            - [ ] Kernel Panic AppleIntelCPUPowerManagement
            - [ ] Kernel Panic AppleACPIPlatform in 10.13
            - [ ] macOS frozen right before login
            - [ ] Keyboard works but trackpad does not
            - [ ] kextd stall[0]: AppleACPICPU
            - [ ] Kernel Panic on AppleIntelI210Ethernet
            - [ ] Kernel panic on "Wrong CD Clock Frequency" with Icelake laptop
            - [ ] Kernel panic on "cckprngintgen"
            - [ ] Stuck at Forcing CS_RUNTIME for entitlement in Big Sur
            - [ ] Stuck on ramrod(^^^^^^^^^^^^^)
            - [ ] Virtual Machine Issues
            - [ ] Reboot on "AppleUSBHostPort::createDevice: failed to create device" on macOS 11.3+
        - [ ] Userspace Issues
            - [ ] macOS installer in Russian
            - [ ] macOS Installer being damaged
            - [ ] Stuck on or near IOConsoleUsers: gIOScreenLock.../gIOLockState (3...
            - [ ] Scrambled Screen on laptops
            - [ ] Black screen after IOConsoleUsers: gIOScreenLock... on laptops and AIOs
            - [ ] Black screen after IOConsoleUsers: gIOScreenLock... on Navi
            - [ ] Frozen in the macOS installer after 30 seconds
            - [ ] 15h/16h CPU reboot after Data & Privacy screen
            - [ ] macOS frozen right before login
            - [ ] MediaKit reports not enough space
            - [ ] DiskUtility failing to erase
            - [ ] SATA Drives Not Shown in DiskUtility
            - [ ] Stuck at 2 minutes remaining
            - [ ] The recovery server cannot get contacted
            - [ ] Keyboard and Mouse broken in Big Sur
            - [ ] Stuck on Your Mac needs a firmware update in order to install to this volume
        - [ ] Post-Install issues
            - [ ] Broken iMessage and Siri
            - [ ] No on-board audio
            - [ ] BIOS reset or sent into Safemode after reboot/shutdown
            - [ ] Synaptics PS2 based trackpad doesn't work
            - [ ] Fix for Dell breakless PS2 keyboard keys
            - [ ] macOS GPU acceleration missing on AMD X570
            - [ ] DRM Broken
            - [ ] "Memory Modules Misconfigured" on MacPro7,1
            - [ ] Apps crashing on AMD
            - [ ] Sleep crashing on AMD
            - [ ] AssetCache Content Caching unavailable in virtual machine
            - [ ] Coffee Lake systems failing to wake
            - [ ] No brightness control on Dual GPU laptops
            - [ ] No temperature/fan sensor output
            - [ ] "You can't change the startup disk to the selected disk" error
            - [ ] Selecting Startup Disk doesn't apply correctly
            - [ ] macOS waking up with the wrong time
            - [ ] No Volume/Brightness control on external monitors
            - [ ] Time inconsistency between macOS and Windows
            - [ ] Disabling SIP
            - [ ] Writing to the macOS system partition
            - [ ] Rolling back APFS Snapshots
            - [ ] Apple Watch Unlock issues
            - [ ] 4K iGPU output issues over HDMI
        - [ ] Miscellaneous issues
            - [ ] Can't run acpidump.efi
            - [ ] Fixing SSDTTime: Could not locate or download iasl!
            - [ ] Fix Python: Python is not installed or not found on PATH
            - [ ] Windows Startup Disk can't see APFS drives
            - [ ] Incorrect resolution with OpenCore
            - [ ] Can't find Windows/BootCamp drive in picker
            - [ ] Selecting Startup Disk doesn't apply correctly
            - [ ] Booting Windows results in BlueScreen or Linux crashes
            - [ ] Booting Windows error: OCB: StartImage failed - Already started
            - [ ] iASL warning, only X unresolved
            - [ ] Time inconsistency between macOS and Windows
    - [ ] OpenCore Debugging
        - [ ] File Swaps
        - [ ] Config Changes
            - [ ] Misc
        - [ ] Disabling all logging
    - [ ] Understanding the macOS boot process
        - [ ] OpenCore booting
        - [ ] boot.efi handoff
        - [ ] XNU/Kernel handoff
        - [ ] macOS handoff
    - [ ] System Debugging: In-depth
        - [ ] EFI setup
        - [ ] config.plist setup
        - [ ] Serial Setup (optional)
        - [ ] Kernel Debug Kits (optional)

- [ ] Post Install
    - [ ] Post-Install (external link)
    - [ ] Universal
        - [ ] Security and FileVault (external link)
        - [ ] Fixing Audio (external link)
        - [ ] Booting without USB (external link)
        - [ ] Updating OpenCore, kexts and macOS (external link)
        - [ ] Fixing DRM (external link)
        - [ ] Fixing iServices (external link)
        - [ ] Fixing Power Management (external link)
        - [ ] Fixing Sleep (external link)
        - [ ] Fixing USB (external link)
    - [ ] Laptop specifics
        - [ ] Fixing Battery read-outs (external link)
    - [ ] Cosmetics
        - [ ] Fixing resolution and verbose (external link)
        - [ ] Add GUI and boot-chime (external link)
    - [ ] Multiboot
        - [ ] OpenCore Multiboot (external link)
        - [ ] Setting up LauncherOption (external link)
        - [ ] Installing BootCamp (external link)
    - [ ] Miscellaneous
        - [ ] Fixing RTC (external link)
        - [ ] Fixing CFG Lock (external link)
        - [ ] Emulated NVRAM (external link)

- [ ] Extras
    - [ ] Fixing KASLR slide values
        - [ ] So what is KASLR
        - [ ] And who is this info for
        - [ ] So how do I fix this
        - [ ] Prepping the BIOS
        - [ ] Test boot
        - [ ] Finding the Slide value
        - [ ] Using DevirtualiseMmio
    - [ ] Disabling dGPU
        - [ ] Windows GPU selection
    - [ ] macOS 12: Monterey
        - [ ] Prerequisites
            - [ ] Supported SMBIOS
            - [ ] Supported hardware
            - [ ] AMD Patches
            - [ ] Bluetooth
            - [ ] Ethernet
            - [ ] OTA Updates
            - [ ] Troubleshooting
    - [ ] Clover conversion (external link)
    - [ ] Choosing the right SMBIOS
        - [ ] How to decide
        - [ ] macOS SMBIOS list
            - [ ] MacBook
            - [ ] MacBook Air
            - [ ] MacBook Pro
            - [ ] Mac Mini
            - [ ] iMac
            - [ ] iMac Pro
            - [ ] Mac Pro
            - [ ] Xserve
            - [ ] Miscellaneous SMBIOS
- [ ] Misc
    - [ ] Supporting the guides
        - [ ] Contributing via issues
        - [ ] Contributing via PRs
            - [ ] How to contribute
            - [ ] Tips
        - [ ] Contributing via translations
    - [ ] Credits

**Comment by dreamwhite** [comment]
Will move `Intel BIOS Settings` onto a separated section
